apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: nvidia
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: yolo_v5
        image: wooks527/yolov5-jetson-nano:latest
        ports:
        - containerPort: 8080
